### ISSUE TITLE
使用main函数的示例代码，传入ts文件，输出的ts文件只有音频流，没有视频流

### ISSUE THREAD

**Issue by liminglu** [akanchi/mpegts#3]
hi，您好，

使用main.cpp，传递一个使用ffmpeg生成的test.ts文件，执行完程序后，输出的test.tsout.ts只有音频流，还请帮助，谢谢。

**Comment by akanchi** [comment]
ffmpeg生成ts的命令相关参数可以提供一下吗？或者提供一下你测试的ts文件

**Comment by liminglu** [comment]
<img width="672" alt="3cd1f8962a6c5967796ab8fc4229b6fb" src="https://user-images.githubusercontent.com/344218/84161701-24f9dc80-aaa2-11ea-88f7-6601694fc34c.png">

@akanchi

**Comment by akanchi** [comment]
这样看不出什么问题，你生成一段测试的ts文件发给我吧

**Comment by akanchi** [comment]
> <img alt="3cd1f8962a6c5967796ab8fc4229b6fb" width="672" src="https://user-images.githubusercontent.com/344218/84161701-24f9dc80-aaa2-11ea-88f7-6601694fc34c.png">
> 
> @akanchi

不过你这张图的tbc有点怪，原test.ts能正常播放吗

**Comment by liminglu** [comment]
> > <img alt="3cd1f8962a6c5967796ab8fc4229b6fb" width="672" src="https://user-images.githubusercontent.com/344218/84161701-24f9dc80-aaa2-11ea-88f7-6601694fc34c.png">
> > @akanchi
> 
> 不过你这张图的tbc有点怪，原test.ts能正常播放吗

@akanchi 源视频是可以播放的，另外输出的test.tsout.flv也是可以的（说明源文件应该好的），详见压缩包
[test.ts.zip](https://github.com/akanchi/mpegts/files/4755849/test.ts.zip)
谢谢。

**Comment by akanchi** [comment]
> > > <img alt="3cd1f8962a6c5967796ab8fc4229b6fb" width="672" src="https://user-images.githubusercontent.com/344218/84161701-24f9dc80-aaa2-11ea-88f7-6601694fc34c.png">
> > > @akanchi
> > 
> > 
> > 不过你这张图的tbc有点怪，原test.ts能正常播放吗
> 
> @akanchi 源视频是可以播放的，另外输出的test.tsout.flv也是可以的（说明源文件应该好的），详见压缩包
> [test.ts.zip](https://github.com/akanchi/mpegts/files/4755849/test.ts.zip)
> 谢谢。

发现问题了，原始ts文件中的视频PID>256, 但是协议中的stream_id字段是8bit的，所以出现pid截断的问题，导致remux后的ts文件视频流识别错误。
可以临时将输的ts文件的流pid改到<=256以解决这个问题。
我有空看一下协议文档看看是否有其他解决的方法。

**Comment by akanchi** [comment]
> > > <img alt="3cd1f8962a6c5967796ab8fc4229b6fb" width="672" src="https://user-images.githubusercontent.com/344218/84161701-24f9dc80-aaa2-11ea-88f7-6601694fc34c.png">
> > > @akanchi
> > 
> > 
> > 不过你这张图的tbc有点怪，原test.ts能正常播放吗
> 
> @akanchi 源视频是可以播放的，另外输出的test.tsout.flv也是可以的（说明源文件应该好的），详见压缩包
> [test.ts.zip](https://github.com/akanchi/mpegts/files/4755849/test.ts.zip)
> 谢谢。

static const uint16_t MPEGTS_PMT_PID = 0x100;
原test.ts中视频流的pid和muxer中定义的pmt_pid冲突了，导致无法识别视频流。
你可以临时修改一下MPEGTS_PMT_PID的值可以解决这个问题。
