### ISSUE TITLE
使用fix #3的提交，测试后还是发现只有音频流，没有视频流

### ISSUE THREAD

**Issue by liminglu** [akanchi/mpegts#4]
【原issue地址】https://github.com/akanchi/mpegts/issues/3#issue-635468719

请帮忙再看下，谢谢。

测试视频还是这个，
[test.ts.zip](https://github.com/akanchi/mpegts/files/4756467/test.ts.zip)

**Comment by akanchi** [comment]
你这个视频我测试remux之后是可以正常播放的，视频信息也都是正确的，和原始流一样
![image](https://user-images.githubusercontent.com/6636640/84234478-ed814380-ab26-11ea-9fa8-cc670e94477a.png)

**Comment by liminglu** [comment]
> 你这个视频我测试remux之后是可以正常播放的，视频信息也都是正确的，和原始流一样
> ![image](https://user-images.githubusercontent.com/6636640/84234478-ed814380-ab26-11ea-9fa8-cc670e94477a.png)

@akanchi 问题定位了，原因是我在create_pes函数中引入了eares处理造成的，再次感谢！
回复效率真高，赞
