### ISSUE TITLE
The 'Multi TS-Packet demux-bug fixed' https://github.com/akanchi/mpegts/pull/6/commits/ae8b73a4783c589afe78bba6ae37fc5b9da7ad86

### ISSUE THREAD

**Issue by andersc** [akanchi/mpegts#7]
The 'Multi TS-Packet demux-bug fixed' https://github.com/akanchi/mpegts/pull/6/commits/ae8b73a4783c589afe78bba6ae37fc5b9da7ad86

Should be cherrypicked and verified.

_Originally posted by @andersc in https://github.com/akanchi/mpegts/pull/6#issuecomment-648113496_

**Comment by akanchi** [comment]
Could you submit pull request base on the main branch? I don't want to change too much codestyle.

**Comment by andersc** [comment]
Since our branches differ so much would it be possible for you to just change the break to continue and then also adjust the buffer as linked to above (if that is correct)? And then you can just close this.
